# Generated by Django 3.2.19 on 2023-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('days_on_zillow', models.IntegerField()),
                ('home_status', models.CharField(max_length=200)),
                ('home_status_for_HDP', models.CharField(max_length=200)),
                ('home_type', models.CharField(max_length=200)),
                ('img_src', models.URLField()),
                ('is_featured', models.BooleanField()),
                ('is_non_owner_occupied', models.BooleanField()),
                ('is_preforeclosure_auction', models.BooleanField()),
                ('is_premier_builder', models.BooleanField()),
                ('is_rental_with_base_price', models.BooleanField()),
                ('is_showcase_listing', models.BooleanField()),
                ('is_unmappable', models.BooleanField()),
                ('is_zillow_owned', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('listing_sub_type', models.CharField(blank=True, max_length=200, null=True)),
                ('living_area', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('price', models.IntegerField()),
                ('price_for_HDP', models.IntegerField()),
                ('rent_zestimate', models.IntegerField()),
                ('should_highlight', models.BooleanField()),
                ('state', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('zpid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
